ProyManage/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^about/', views.about),
    re_path(r'^$',views.home, name="home"),
    re_path(r'^accounts/',include('accounts.urls')),
    re_path(r'^proyects/',include('proyects.urls'))
]

accounts/urls.py
from django.urls import path, include, re_path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = 'accounts'

urlpatterns = [
    re_path(r'^logup/$', views.logup_view, name='logup'),
    re_path(r'^login/$', views.login_view, name='login'),
    re_path(r'^logout/$', views.logout_view, name= 'logout'),
]

proyects/urls.py
from django.urls import path, re_path
from . import views

app_name = 'proyects'

urlpatterns = [
    re_path(r'^lista/$', views.lista_proy, name='lista'),
    re_path(r'^crear/$', views.create_proy, name='crear'),
    #re_path(r'^proy(?P<shortname>+)/$', views.detalles_art,name ='detalle'),
    re_path(r'^detalle/(?P<shortname>[\w-]+)$', views.detalles_proy, name='detalle'),
    #re_path(r'^(?P<proy>[\w-]+)/$', views.create_task,name ='crear_task')
    #re_path(r'^(/taskhistory/ + ?P<proy>[\w-])/$', views.create_task , 'crear_task'),

]

proyects/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms

unit_choices = (
    ('Hours', 'Hours'),
    ('Days', 'Days'),
    ('Months', 'Months'),
    )

class Project(models.Model):

    shortname = models.CharField(max_length = 20, unique = True)
    name = models.CharField(max_length = 200)
    owner = models.ForeignKey(User, default=None,on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField(null = True)
    is_active = models.BooleanField(default = True)
    created_on = models.DateTimeField(auto_now_add = 1)

    def __str__(self):
        return self.name


class Task(models.Model):
    #tareas
    number = models.IntegerField()
    name = models.CharField(max_length=200)
    project = models.ForeignKey(Project, default=None,on_delete=models.CASCADE)
    parent_task_num = models.IntegerField(null=True, blank=True) # si tiene id de tarea es una subtarea
    user_responsible = models.ForeignKey(User, null=True, blank=True, default=None,on_delete=models.CASCADE)#responsable de la tarea
    expected_start_date = models.DateField() #Estimado de inicio
    expected_end_date = models.DateField(null=True, blank=True) #Estimado de fin
    actual_start_date = models.DateField(null=True, blank=True)
    actual_end_date = models.DateField(null=True, blank=True)
    is_complete = models.BooleanField(default=False) #tarea completada
    created_on = models.DateTimeField(auto_now_add=1) #fecha creacion
    is_deleted = models.BooleanField(default=False) #marcada como eliminada
    created_by = models.ForeignKey(User, related_name='created_tasks', default=None,on_delete=models.CASCADE)
    last_updated_by = models.ForeignKey(User, related_name='updated_tasks', default=None,on_delete=models.CASCADE)
    # Versioning
    effective_start_date = models.DateTimeField(auto_now_add=True)
    effective_end_date = models.DateTimeField(null=True, auto_now=True)
    version_number = models.IntegerField()
    is_current = models.BooleanField(default=True)


class TaskItem(models.Model):
    #sub tareas
    number = models.IntegerField()
    project = models.ForeignKey(Project, default=None,on_delete=models.CASCADE)
    task_num = models.IntegerField()
    name = models.CharField(max_length=200)
    user = models.ForeignKey(User, null=True, default=None,on_delete=models.CASCADE)
    expected_time = models.DecimalField(decimal_places=2, max_digits=10)
    actual_time = models.DecimalField(decimal_places=2, max_digits=10, null=True)
    unit = models.CharField(max_length=20, choices=unit_choices)
    is_complete = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=1)
    created_by = models.ForeignKey(User, related_name='created_taskitems', default=None,on_delete=models.CASCADE)
    last_updated_by = models.ForeignKey(User, related_name='updated_taskitems', default=None,on_delete=models.CASCADE)
    is_deleted = models.BooleanField(default=False)
    # Versioning
    effective_start_date = models.DateTimeField(auto_now_add=1)
    effective_end_date = models.DateTimeField(null=True)
    version_number = models.IntegerField()
    is_current = models.BooleanField(default=True)


class TodoList(models.Model):
    # lista de tareas de un usuario
    name = models.CharField(max_length = 200)
    user = models.ForeignKey(User, default=None,on_delete=models.CASCADE)
    project = models.ForeignKey(Project, default=None,on_delete=models.CASCADE)
    is_complete_attr = models.BooleanField(default = False)
    created_on = models.DateTimeField(auto_now_add = 1)

class TaskNote(models.Model):
    #notas de tareas
    task_num = models.IntegerField()
    text = models.TextField()
    user = models.ForeignKey(User, default=None,on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add = 1)

proyects/forms.py
from django.forms import ModelForm, Textarea, TextInput, URLInput
from . import models



class create_proyect(ModelForm):
    class Meta:
        model = models.Project
        fields=['shortname','name','owner', 'start_date','end_date','is_active']

class create_task(ModelForm):
    class meta:
        model = models.Task
        fields=['name','project','parent_task_num','user_responsible','expected_start_date','expected_end_date','actual_start_date','actual_end_date','is_complete','created_on','is_deleted','created_by','last_updated_by']

proyects/views.py
from django.shortcuts import render, redirect
from .models import Task,TaskItem,TaskNote,TodoList,Project
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

from django.db import transaction

from sequences import get_next_value


# Create your views here.

def lista_proy(request):
    proyects = Project.objects.all()

    return render(request,'proyects/list_proy.html',{'proyects': proyects})

def detalles_proy(request, shortname):

    proyects = Project.objects.get(shortname=shortname)

    return render(request,'proyects/det_proy.html',{'proyects': proyects})

@login_required(login_url="/accounts/login/")
def create_proy (request):
    if request.method =='POST':
        form = forms.create_proyect(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.owner = request.user
            instance.save()
            return redirect('proyects:lista')
    else:
        form = forms.create_proyect()
    return render(request, 'proyects/create_proy.html', {'form':form})
"""
def create_task(request,proy):
    if request.method =='POST':
        form = forms.create_task(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.owner = request.user
            instance.project = proy
            instance.number = get_next_value('shortname')
            instance.save()
            return redirect('proyects:detalle')
    else:
        form = forms.create_task(proy)
    return render(request, 'proyects/create_task.html', {'form':form})
"""

proyects/templates/proyects/create_proy.html
{% extends 'base_layout.html'%}

{% block content%}
    <p1>Crear Proyecto</p1>
    <div class="create-proyecto">
        <h2>Crear un nuevo proyecto</h2>
        <form class = "site-form" action="{% url 'proyects:crear'%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
              <p>
                {% if field.label_tag == 'Start Date' %}
                    <p1>Crear kahjskd</p1>
                {% else %}
                  {{ field.label_tag }}<br>
                  {{ field }}
                {% endif %}

                {% if field.help_text %}
                  <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                  <p style="color: red">{{ error }}</p>
                {% endfor %}
              </p>

            {% endfor %}

            <input type="submit" value="Crear">
        </form>
    </div>
{% endblock%}

proyects/templates/proyects/create_task.html
{% extends 'base_layout.html'%}

{% block content%}
    <p1>Crear Tarea</p1>
    <div class="create-task">
        <h2>Crear un nueva tarea</h2>
        <form class = "site-form" action="{% url 'proyects:crear_task' proy=proy.shortname %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
              <p>
                {{ field.label_tag }}<br>
                {{ field }}

                {% if field.help_text %}
                  <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                  <p style="color: red">{{ error }}</p>
                {% endfor %}
              </p>

            {% endfor %}

            <input type="submit" value="Crear">
        </form>
    </div>
{% endblock%}

proyects/templates/proyects/det_proy.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="detalle_proy">
    <br class="proyects">
        <label>Nombre: <a >{{proyects.shortname}}</a> </label></br>
        <label>Nombre Completo: <a>{{proyects.name}}</a> </label></br>
        <label>Asignado: <a>{{proyects.owner}}</a> </label></br>
        <label>Fecha Inicio: <a>{{proyects.start_date}}</a> </label></br>
        <label>Fecha Fin: <a>{{proyects.end_date}}</a> </label></br>
        <label>Activo?<input type="checkbox"{% if proyects.is_active %} checked="checked"{% endif %}></label></br>
        <label>Fecha Creacion: <a>{{proyects.created_on}}</a> </label></br>
</div>

<!--<a href="{% url 'proyects:crear_task' proy=proyects.shortname %}" class="button">Crear Tarea</a>-->

{% endblock %}

proyects/templates/proyects/list_proy.html
{% extends 'base_layout.html'%}

{% block content%}
    <u><h2>Lista de Proyectos</h2></u> </br>
    <div class="proyects">
        {% for proy in proyects %}

            <div class="proyects">
                <h3><a href="{% url 'proyects:detalle' proyects.shortname%}">{{ proy.name }}</a> </h3>
            </div>
        {% endfor %}
    </div>

    <a href="#" class="button">Crear Proyecto</a>
{% endblock%}

{% url 'proyects:crear' %}

proyects/templates/proyects/prueba.html
{% extends 'base_layout.html'%}
{% block content%}
<p1>Crear Proyecto</p1>
<div class="create-proyecto">
  <h2>Crear un nuevo proyecto</h2>
  <form class = "site-form" action="{% url 'proyects:crear'%}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row field-shortname">
      <div>
        <label class="required" for="id_shortname">Shortname:</label>
        <input type="text" name="shortname" value="PruCom" class="vTextField" maxlength="20" required="" id="id_shortname">
      </div>
    </div>
    <div class="form-row field-name">
      <div>
        <label class="required" for="id_name">Name:</label>
        <input type="text" name="name" value="Prueba Comision" class="vTextField" maxlength="200" required="" id="id_name">
      </div>
    </div>
    <div class="form-row field-owner">
      <div>
        <label class="required" for="id_owner">Owner:</label>
        <div class="related-widget-wrapper">
          <select name="owner" required="" id="id_owner">
            <option value="">---------</option>
          </select>
        </div>
      </div>
    </div>
    <div class="form-row field-start_date">
      <div>
        <label class="required" for="id_start_date">Start date:</label>
        <input type="text" name="start_date" value="01/01/2018" class="vDateField" size="10" required="" id="id_start_date">
          <span class="datetimeshortcuts">&nbsp;
              <a href="#" id="calendarlink0">
              </a>
          </span>
        <br><span class="timezonewarning">Nota: Ud. se encuentra en una zona horaria que est&aacute; 3 horas atrasada respecto a la del servidor.</span>
      </div>
    </div>
    <div class="form-row field-end_date">
      <div>
        <label class="required" for="id_end_date">End date:</label>
        <input type="text" name="end_date" value="31/01/2018" class="vDateField" size="10" required="" id="id_end_date">
          <span class="datetimeshortcuts">&nbsp;
              <a href="#" id="calendarlink1">
              </a>
          </span>
        <br>
          <span class="timezonewarning">Nota: Ud. se encuentra en una zona horaria que est&aacute; 3 horas atrasada respecto a la del servidor.</span>
      </div>
    </div>
    <div class="form-row field-is_active">
      <div class="checkbox-row">
        <input type="checkbox" name="is_active" id="id_is_active" checked="">
          <label class="vCheckboxLabel" for="id_is_active">Is active</label>
      </div>
    </div>
    <input type="submit" value="Crear">
  </form>
</div>
{% endblock%}


{% load crispy_forms_filters %}
{% load l10n %}

<div class="controls {{ field_class }}"{% if flat_attrs %} {{ flat_attrs|safe }}{% endif %}>
    {% include 'bootstrap3/layout/field_errors_block.html' %}

    {% for choice in field.field.choices %}
        <div class="checkbox{% if inline_class %}-{{ inline_class }}{% endif %}">
            <label>
                <input type="checkbox"{% if choice.0 in field.value or choice.0|stringformat:"s" in field.value or choice.0|stringformat:"s" == field.value|stringformat:"s" %} checked="checked"{% endif %} name="{{ field.html_name }}" id="id_{{ field.html_name }}_{{ forloop.counter }}" value="{{ choice.0|unlocalize }}" {{ field.field.widget.attrs|flatatt }}>{{ choice.1|unlocalize }}
            </label>
        </div>
    {% endfor %}

    {% include 'bootstrap3/layout/help_text.html' %}
</div>




<a href="{% url 'proyects:crear_task' proy=proyects.shortname %}" class="button">Crear Tarea</a>