ProyManage/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^about/', views.about),
    re_path(r'^$',views.home, name="home"),
    re_path(r'^accounts/',include('accounts.urls')),
    re_path(r'^proyects/',include('proyects.urls'))
]

accounts/urls.py
from django.urls import path, include, re_path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = 'accounts'

urlpatterns = [
    re_path(r'^logup/$', views.logup_view, name='logup'),
    re_path(r'^login/$', views.login_view, name='login'),
    re_path(r'^logout/$', views.logout_view, name= 'logout'),
]

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sobre CRUD Django</title>
</head>
<body>
    <p1>Aplicacion creada por Martin Moldes</p1>
</body>
</html>

templates/base_layout.html
{% load static from staticfiles%}
<html lang="en">
    <head>

        <meta charset="UTF-8">
        <title>Proyectos</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script rel="stylesheet" href="{% static 'jquery-3.3.1.min.js' %}"></script>
        <script rel="stylesheet" href="{% static 'bootstrap.min.js' %}"></script>

    </head>
    <body>
        <header class="wrapper">

            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <div class="navbar-header">
                      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                        <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'logo.jpg' %}"/></a>
                    </div>
                </div>
                <div class="container-fluid">
                    <ul class="nav navbar-nav">
                        <li><a href="#">Proyectos</a></li>
                        <li><a href="#">About</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                        <li>
                            <a href="#">
                                <form class = "logout-link" action="{% url 'accounts:logout' %}" method="POST">
                                    {% csrf_token %}
                                    <button class="btn btn-link" type="submit"><span class="glyphicon glyphicon-log-in"></span> Logout</button>

                                </form>
                        </li>
                        {% else %}
                        <li>
                            <a href="{% url 'accounts:login'%}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:logup'%}">Registrar</a>
                        </li>
                        {% endif%}
                    </ul>
                </div>
            </nav>

        </header>
        <div class = "wrapper">
            {% block content%}
            {% endblock %}
        </div>
    </body>
</html>

templates/home.html
{% extends 'base_layout.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    <h1>Tincho</h1>
</body>
</html>